import WorkoutList from "@/components/ WorkoutList";
import AddWorkoutModal from "@/components/AddWorkoutButton";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { useAuthContext } from "@/hooks/useAuthContext";
import { useRouter } from "next/router";
import { useEffect } from "react";

type Props = {
  user: string;
};

export default function Home() {
  const { user } = useAuthContext() as Props;

  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push("/");
    }
    if (!user) {
      router.push("/login");
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen bg-gray-100">
        <Navbar />
        <AddWorkoutModal />
        <WorkoutList />
      </main>
    </>
  );
}
