import WorkoutList from "@/components/ WorkoutList";
import AddWorkoutModal from "@/components/AddWorkoutButton";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen bg-gray-100">
        <Navbar />
        <AddWorkoutModal />
        <WorkoutList />
      </main>
    </>
  );
}
